spring:
  application:
    name: haochi

---
spring:
  profiles: default
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create
    show-sql: false

haochi:
  message: Hello, world!